### ISSUE TITLE
Beat Saberのコミュニティとの共有

### ISSUE THREAD

**Issue by hedo29** [rynan4818/bs-movie-cut#1]
バグや問題ではありませんのでご注意ください。

(日本語があまり上手ではないのでDeepLを使っています、〜N4です。翻訳が間違っていたら申し訳ありません)。

opl-さんのプロジェクトで課題が開かれているのを見ました。もしこのツールをより多くの人と共有したいのであれば、他にもたくさんのBeat Saberツールを持っている国際的なDiscordサーバーがあります。サーバーの招待は https://discord.gg/beatsabermods (チャンネル -> #pc-mods) です。

このサーバーはほとんどが英語ですが、他のプレイヤーはドキュメントを理解できるかもしれません。DeepLはかなり翻訳してくれるようです。

お疲れ様でした! 他のプレイヤーにも使ってもらえるといいですね! opl-さんのプロジェクトとは直接関係ないので、他の方と共有できるようでしたら、私に直接ご連絡ください。

ツイッター: @\_Hedonic\_
Discord: Hedonic#7926

**Comment by rynan4818** [comment]
お返事が遅れてしまい申し訳ありません。

アドバイス頂き、ありがとうございます。

opl-さんのプロジェクトに投稿した課題で、opl-さんから返信をもらいましたが、いくつか問題点の指摘を受けました。
その指摘内容はとても理解できるものであったので、このままツールをサポートが困難な海外の方にまで広げてしまうのは問題があると感じました。

Beat Saber Modding GroupのDiscordサーバは私も参加していますが、情報収集の閲覧のみで参加しており投稿はしておりません。
私自身が英語が苦手なことと、大量の投稿を日々追っていくのは難しいと感じています。

せっかく作成したツールなので、opl-さんのプロジェクトで紹介の投稿はしましたが、Beat Saber Modding GroupのDiscordサーバで私自身が紹介するのは、サポートが難しいため避けたいと思います。

ただ、他の方が私のツールを紹介するのは、全く問題ありません。
BeatSaberで遊んだ動画をtwitterやyoutubeに投稿したりする際に、便利なツールだと思うので海外の方にも使っていただけたらとは思っています。

(DeepLは便利ですね、英語から日本語でも非常に上手に翻訳してくれます。上の文はDeepLで英語に翻訳したあと、日本語に翻訳し直して確認しました。）
